--CLIENT
--Хранит клиентов 
CREATE TABLE MS.dbo.CLIENT (
  ID int IDENTITY,
  NAME varchar(50) NOT NULL,
  CONSTRAINT PK_CLIENT PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT KEY_CLIENT_NAME UNIQUE (NAME)
)
ON [PRIMARY]
GO
--PRODUCT
--Хранит товары 
CREATE TABLE MS.dbo.PRODUCT (
  ID int IDENTITY,
  NAME varchar(50) NOT NULL,
  CONSTRAINT PK_PRODUCT_ID PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT KEY_PRODUCT_NAME UNIQUE (NAME)
)
ON [PRIMARY]
GO
--SALES
--Хранит продажи 
CREATE TABLE MS.dbo.SALES (
  ID int IDENTITY,
  DATE datetime NOT NULL,
  ID_CLIENT int NOT NULL,
  SUMM money NULL,
  DATE_CREATE datetime NULL,
  VERIFICATION bit NULL DEFAULT (0),
  DATE_VERIFICATION datetime NULL,
  CONSTRAINT PK_SELES_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO
ALTER TABLE MS.dbo.SALES
  ADD CONSTRAINT FK_SELES_ID_CLIENT FOREIGN KEY (ID_CLIENT) REFERENCES dbo.CLIENT (ID)
GO
--SELES_CONTENTS
--Хранит товары в продажаъ
CREATE TABLE MS.dbo.SALES_CONTENTS (
  ID int IDENTITY,
  ID_SALES int NOT NULL,
  ID_PRODUCT int NOT NULL,
  QTY int NOT NULL,
  PRICE money NOT NULL,
  SUMM money NULL,
  CONSTRAINT PK_SELES_CONTENTS_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO
ALTER TABLE MS.dbo.SALES_CONTENTS
  ADD CONSTRAINT FK_SELES_CONTENTS_ID_PRODUCT FOREIGN KEY (ID_PRODUCT) REFERENCES dbo.PRODUCT (ID)
GO
ALTER TABLE MS.dbo.SALES_CONTENTS
  ADD CONSTRAINT FK_SELES_CONTENTS_ID_SELES FOREIGN KEY (ID_SALES) REFERENCES dbo.SALES (ID)
GO 
