--TRG_SALES_DATE
--Триггер служит для: формирования даты создания продажи, формирование даты подтверждения продажи, обнуление даты продажи в случае отмены подтверждения.
CREATE TRIGGER dbo.TRG_SALES_DATE
ON dbo.SALES
AFTER INSERT, UPDATE
AS
BEGIN

    UPDATE SALES
    SET SALES.DATE_CREATE = GETDATE()
    FROM INSERTED
    WHERE SALES.ID = INSERTED.ID
    AND SALES.DATE_CREATE IS NULL;

    UPDATE SALES
    SET SALES.DATE_VERIFICATION = GETDATE()
    FROM INSERTED
    WHERE SALES.ID = INSERTED.ID
    AND INSERTED.VERIFICATION = 1;

    UPDATE SALES
    SET SALES.DATE_VERIFICATION = NULL
    FROM INSERTED
    WHERE SALES.ID = INSERTED.ID
    AND INSERTED.VERIFICATION = 0;

END
GO
 
--TRG_SALES_DELETE
--Триггер служит для удаление товаров в документе при удалении продажи.
CREATE TRIGGER dbo.TRG_SALES_DELETE
ON dbo.SALES
INSTEAD OF DELETE
AS
BEGIN
  DELETE SALES_CONTENTS
    FROM DELETED
  WHERE DELETED.ID = ID_SALES;
  DELETE SALES 
    FROM DELETED
  WHERE DELETED.ID = SALES.ID;
END
GO
--TGR_SALES_CONTENTS_DEL
--Триггер служит для обновления суммы товара и общей суммы продажи при удалении.
CREATE TRIGGER dbo.TGR_SALES_CONTENTS_DEL
ON dbo.SALES_CONTENTS
AFTER DELETE
AS 
BEGIN


   UPDATE SALES_CONTENTS
  SET SALES_CONTENTS.SUMM = SALES_CONTENTS.QTY * SALES_CONTENTS.PRICE
  FROM DELETED
  WHERE DELETED.ID = SALES_CONTENTS.ID;

  UPDATE SALES
  SET SALES.SUMM = (SELECT
      SUM(SC.SUMM)
    FROM SALES_CONTENTS SC
    JOIN DELETED
      ON SC.ID_SALES = DELETED.ID_SALES)
  FROM DELETED
  WHERE SALES.ID = DELETED.ID_SALES



END
GO
--TGR_SALES_CONTENTS_UPD
--Триггер служит для обновления суммы товара и общей суммы продажи при обновлении.
CREATE TRIGGER dbo.TGR_SALES_CONTENTS_UPD
ON dbo.SALES_CONTENTS
AFTER INSERT, UPDATE
AS 
BEGIN


   UPDATE SALES_CONTENTS
  SET SALES_CONTENTS.SUMM = SALES_CONTENTS.QTY * SALES_CONTENTS.PRICE
  FROM INSERTED
  WHERE INSERTED.ID = SALES_CONTENTS.ID;

  UPDATE SALES
  SET SALES.SUMM = (SELECT
      SUM(SC.SUMM)
    FROM SALES_CONTENTS SC
    JOIN INSERTED
      ON SC.ID_SALES = INSERTED.ID_SALES)
  FROM INSERTED
  WHERE SALES.ID = ID_SALES



END
GO
--TRG_SALES_REVIEW
--Триггер служит для: ограничения вввода данных в поле суммы.
CREATE TRIGGER dbo.TRG_SALES_REVIEW
ON dbo.SALES
AFTER INSERT, UPDATE 
AS
BEGIN
 declare @VAR_SUMM int;
 SELECT
    @VAR_SUMM = SUM(SC.SUMM) - INSERTED.SUMM
 FROM SALES_CONTENTS AS SC
  JOIN INSERTED
    ON SC.ID_SALES = INSERTED.ID
 GROUP BY SC.ID_SALES
          ,INSERTED.SUMM;

IF NOT @VAR_SUMM = 0
BEGIN
  ROLLBACK TRAN
  RAISERROR ('Редактировать поле суммы запрещено', 16, 0);
  RETURN
END

END
GO